# Generated by Django 5.2.2 on 2025-06-09 08:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('fishapi', '0004_order_orderitem'),
    ]

    operations = [
        migrations.AddField(
            model_name='productoption',
            name='is_available',
            field=models.BooleanField(default=True),
        ),
    ]
